# Generated by Django 4.0.1 on 2022-10-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrierServiceID', models.CharField(choices=[('fedexAIR', 'fedexAIR'), ('fedexGroud', 'fedexGroud'), ('PSExpress', 'PSExpress'), ('UPS2DAY', 'UPS2DAY')], max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
